### ISSUE TITLE
setting on vim-autosave wrong

### ISSUE THREAD

**Issue by 3xp10it** [chrisbra/vim-autosave#1]
when i tried to set 
:let g:autosave_timer= 3000
then I typed:
:AutoSave
to get information from vim-autosave,it shows me:
No AutoSave Timer active,can you help me?
                                        Thx.

**Comment by 3xp10it** [comment]
I solved it by below:
:let g:autosave_timer= 3
it works.

however,when i changed one file,and wait for 3 seconds,then typed:
:q!
and reopen the file, but didn't find the file has been changed(not svaed),can you can me?
     Thx.

**Comment by chrisbra** [comment]
this plugin saves copies of the actual working file within your `'backupdir'` path. it does not change your current file.
