### ISSUE TITLE
Bug report: not working on Windows 10.

### ISSUE THREAD

**Issue by kgfly** [chrisbra/vim-autosave#4]
Observed:
I manually create C:\Users\user_name\\.vim\backup. And start gvim.
However, C:\Users\user_name\.vim\backup is always an empty dir.

Expected: 
C:\Users\user_name\.vim\backup should have backup files.

.vimrc:

" ----------------------------------------------
" vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'chrisbra/vim-autosave'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:-----
" ----------------------------------------------

let g:autosave_timer = 10*1000

Gvim version: 8.2.416

Thanks.

**Comment by kgfly** [comment]
@chrisbra , do you have any suggestions? Thanks for helping~. Really appreciate.

**Comment by chrisbra** [comment]
sorry, I am currently busy with a lot of other things. Might take a bit until I come to this.

**Comment by kgfly** [comment]
Thanks, @chrisbra . Please take your time.

On Ubuntu 20 LTS, Vim 8.1. The plugin works. So it could be a Windows OS issue. (like it cannot recognize "~" as home folder)

**Comment by kgfly** [comment]
On Ubuntu 20 LTS,  I found a minor issue, comparing to Windows' block issue.

Repro.
Use above .vimrc.
Do not manually create folder /.vim/backup

Observed:
The backup files are saved to ~ folder, home folder.

Expected:
The plugin should create /.vim/backup and save the backup files to /.vim/backup.

**Comment by kgfly** [comment]
Hi @chrisbra , the issue still repro with latest commit. May you please take a look when you have time?

Basically,

let g:autosave_timer = 10*1000
let g:autosave_extensions = '.backup'
let g:autosave_backup = '~/.vim/backup'

only work on Linux, but not on Windows.

Thanks in advance.

**Comment by kgfly** [comment]
Hi @chrisbra , I also verify that it works on Mac. This is a useful plugin. May you please kindly take a look what's wrong on Windows 10? Thanks.

**Comment by chrisbra** [comment]
what is `g:autosave_backupdir` in your case? Does `:echo g:autosave_errors` echo anything?

**Comment by chrisbra** [comment]
Hm, can it be that this:

> let g:autosave_backup = '~/.vim/backup'

Needs to be 

    let g:autosave_backup = expand('~/.vim/backup')

?

**Comment by kgfly** [comment]
Not working. Once applying the change, under .vim/backup folder, I notice a wired file. 

![image](https://user-images.githubusercontent.com/12282281/96291516-fedad080-0f9c-11eb-89bc-32359fc225cd.png)

@chrisbra , any suggestion?

**Comment by chrisbra** [comment]
I don't know. Depends on what you did...

did you try this:

    let g:autosave_backup = expand('~/.vim/backup')

Did you check this:

> what is g:autosave_backupdir in your case? Does :echo g:autosave_errors echo anything?

**Comment by kgfly** [comment]
I've tried

let g:autosave_backup = expand('~/.vim/backup')

It's not working.

echo g:autosave_errors prompted this error

![image](https://user-images.githubusercontent.com/12282281/98343021-0d2d7280-1fc6-11eb-95fa-a5f9e1b9ad7c.png)

**Comment by chrisbra** [comment]
what is the file name and the path of the file?

**Comment by kgfly** [comment]
The weird thing is: I cannot repro the error. I have tried various file. It no longer repro.

Now echo g:autosave_errors  always prompted:

![image](https://user-images.githubusercontent.com/12282281/98456472-feb09980-2132-11eb-9d7a-1143772b94d1.png)

**Comment by kgfly** [comment]
@chrisbra , Thanks.

Though I am not a vim expert, I did some debugging:

I think I know the reason.

![image](https://user-images.githubusercontent.com/12282281/98482426-1846f500-21b6-11eb-85f5-8a69705545d5.png)

The script is trying to write a file name: "C:=+Users=+k=+ttt=+1_20201108_1131." However, on Windows ":" cannot be used as a part of the file name. 

May you please work on a fix? On Windows, maybe replace ":" by "#" before writing?

(BTW,  autosave.vim.backup seems unused. May you please remove it too?)

**Comment by kgfly** [comment]
I have one more a question: does the script do some auto cleanup for the backup files under backup folder? Or it just left then under the folder forever.

**Comment by chrisbra** [comment]
yeah, I noticed something similar too. Needs a bit of more work.

> I have one more a question: does the script do some auto cleanup for the backup files under backup folder? Or it just left then under the folder forever.

No, by default they will stay there. in general I do not like the idea of auomatically deleting some files by the plugin. But there is the `autosave_max_copies` setting, see commit b68b2e1bb2d7c08441369be8ced22d9c373b724e which should do what you want.

**Comment by kgfly** [comment]
autosave_max_copies should be good to me. Thanks.

**Comment by chrisbra** [comment]
okay, I think I have fixed your issues now finally.

**Comment by kgfly** [comment]
Yes. Verified. Thanks for helping~
