### ISSUE TITLE
Feature request: set an upper limit for backup file size.

### ISSUE THREAD

**Issue by kgfly** [chrisbra/vim-autosave#8]
Set an upper limit for backup file size.
Add a new option. let g:autosave_backup_max_filesize
When during backup, only backup file when the file size is smaller than autosave_backup_max_filesize.

Please correct me if I am wrong. Currently, if I open a 1GB file, make minor edit, it will be backup too, which is not necessary.

Thanks in advance.

**Comment by kgfly** [comment]
@chrisbra , may you please help on this request?

**Comment by chrisbra** [comment]
will have a look at it, thanks for pinging me again, I didn't notice the original request.

**Comment by kgfly** [comment]
Thanks @chrisbra . If possible, please add these 2 options:

g:autosave_backup_max_filesize # set upper file size limit.
g:autosave_only_text # Only backup text file, not binary files.

**Comment by kgfly** [comment]
Thanks @chrisbra . 

What's the unit of g:autosave_backup_max_filesize ? B/KB/MB?

Also may you please add these 2 switches to readme?

Thanks again?

**Comment by kgfly** [comment]
Sounds "byte. "
